ecommerce_proj/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('users_app.urls')),
    path('', include('shop_app.urls')),
    path('payments/', include('payments_app.urls')),
]

shop_app/urls.py
from django.urls import path

from . import views

app_name='shop_app'

urlpatterns = [
    path('', views.index, name='index'),
    path('add-to-cart/<int:product_id>', views.add_to_cart, name='add_to_cart'),
    path('remove-from-cart/<int:cart_item_id>', views.remove_from_cart, name="remove_from_cart"),
    path('update-cart-item/<int:cart_item_id>', views.update_cart_item, name='update_cart_item')
]

templates/shop/_pagination.html
<nav aria-label="Page navigation example">
    <ul class="pagination">
        <li class="
                page-item
                {% if not products_page.has_previous %}
                    disabled
                {% endif %}
            ">
            <a class="page-link" href="?page_number=1" aria-label="First">
                <span aria-hidden="true">&laquo; First</span>
            </a>
        </li>
        <li class="
                page-item
                {% if not products_page.has_previous %}
                    disabled
                {% endif %}
            ">
            <a class="page-link" {% if products_page.has_previous %}
                href="?page_number={{products_page.previous_page_number}}" {% endif %} aria-label="Previous">
                <span aria-hidden="true">Prev</span>
            </a>
        </li>
        <li class="page-item"><a class="page-link" href="#">{{products_page.number}}</a></li>
        <li class="
                page-item
                {% if not products_page.has_next %}
                    disabled
                {% endif %}
            ">
            <!-- build the link with an href that includes the number of the next page -->
            <a class="page-link" {% if products_page.has_next %} href="?page_number={{products_page.next_page_number}}"
                {% endif %} aria-label="Next">
                <span aria-hidden="true">Next</span>
            </a>
        </li>
        <li class="
                page-item
                {% if not products_page.has_next %}
                    disabled
                {% endif %}
            ">
            <a class="page-link" href="?page_number={{products_page.paginator.num_pages}}" aria-label="Last">
                <span aria-hidden="true">Last &raquo;</span>
            </a>
        </li>
    </ul>
</nav>

templates/shop/_product-filter-form.html
<div class="col-12 col-md-3 pt-5">
    <form action="{% url 'shop_app:index' %}" method="POST" class="container">
        <div class="row">

            <!-- SEARCH QUERY TEXT INPUT -->
            <fieldset class="col-12 form-group mt-3">
                <label for="search-query" class="form-label w-100">
                    <h5 class="h5">Query</h5>
                    <input type="text" id="search-query" name="search-query" value="{{form_data.search_query}}" class="form-control">
                </label>
            </fieldset>


            <!-- ORDER BY SELECT MENU -->
            <fieldset class="col-12 form-group mt-3">
                <label for="order-by" class="w-100">
                    <h5 class="h5">Order By</h5>
                    <select name="order-by" id="order-by" class="form-select">
                        <!-- LOOP THROUGH THE ORDER_BY OPTIONS AND RENDER AN OPTION TAG FOR EACH -->
                        {% for option in search_options.order_by_options %}
                        <!-- use conditional rendering to select the option from the form -->
                        <option 
                            value="{{option.value}}"
                            {% if option.value == form_data.order_by %}
                                selected
                            {% endif %}
                        >
                            {{option.label}}
                        </option>
                        {% endfor %}
                    </select>
                </label>
            </fieldset>


            <!-- CATEGORY CHECKBOXES -->
            <fieldset class="col-12 d-flex flex-column mt-3">
                <h5 class="h5">Categories</h5>
                <!-- LOOP THROUGH ALL THE CATEGORES AND CREATE A CHECKBOX FOR EACH -->
                {% for category in search_options.categories %}

                <label for="category-{{category.id}}">
                    <!-- use conditional rendering to check the boxes that are in the categories list -->
                    <input 
                        type="checkbox"
                        id="category-{{category.id}}"
                        name="categories"
                        value="{{category}}"
                        {% if category in form_data.categories %}
                            checked
                        {% endif %}
                    />
                    {{category|title}}
                </label>
                {% endfor %}
            </fieldset>


            <!-- MAX/MIN PRICE -->
            <fieldset class="col-5 d-flex flex-column gap-2 mt-3">
                <h5 class="h5">Price</h5>
                <label for="min-price">Min
                    <input type="number" id="min-price" name="min-price" value="{{form_data.min_price}}" class="form-control">
                </label>
                <label for="max-price">Max
                    <input type="number" id="max-price" name="max-price" value="{{form_data.max_price}}" class="form-control">
                </label>
            </fieldset>
            
            
            <!-- MAX/MIN RATING -->
            <fieldset class="col-5 d-flex flex-column gap-2 mt-3">
                <h5 class="h5">Rating</h5>
                <label for="min-rating">Min
                    <input type="number" id="min-rating" name="min-rating" value="{{form_data.min_rating}}" class="form-control">
                </label>
                <label for="max-rating">Max
                    <input type="number" id="max-rating" name="max-rating" value="{{form_data.max_rating}}" class="form-control">
                </label>
            </fieldset>

            {% csrf_token %}

            <!-- SUBMIT BUTTON -->
            <div class="col-4 offset-4 d-flex justify-content-center">
                <button type="submit" class="btn btn-success mt-3">Submit</button>
            </div>
        </div>
    </form>
</div>

templates/shop/index.html
{% extends 'layout/base.html' %}

{% block content %}

<h1 class="h1 text-center">eCommerce App</h1>


<div class="row d-flex">
    <div class="col-12 d-flex justify-content-center">
        {% include 'shop/_pagination.html' with products_page=products_page %}
    </div>

    <!-- include the filter form -->
    {% include 'shop/_product-filter-form.html' %}

    <!-- RENDER CARD FOR EACH PRODUCT IN THE LIST -->
    {% for product in products_page %}

    <div class="col-12 col-md-6 col-lg-4">
        <div class="card mt-4 shadow">

            <!-- PRODUCT IMAGE -->
            <img src="{{ product.image_url }}" alt="{{product.title}}" class="card-img-top mx-auto my-4"
                style="width:10rem;">




            <!-- CARD BODY -->
            <div class="card-body">
                <h5 class="card-title">{{product.title}}</h5>

                <p class="d-flex">
                    Rated {{product.rating}} / 5 by {{product.rating_count}} users
                </p>

                <h3 class="h3">${{product.price}}</h3>

                <p class="card-text">
                    <!-- LIMIT DESCRIPTION TO 20 WORDS -->
                    {{ product.description|truncatewords:20 }}
                </p>

                <p class="card-text">
                    {% for category in product.categories.all %}

                <div class="badge bg-info p-2 my-1">
                    <!-- format the product categories in TitleCase with the |title filter -->
                    {{ category.title|title }}
                </div>
                {% endfor %}
                </p>
            </div>
            <!-- END CARD BODY -->





            <!-- CARD FOOTER -->
            <div class="card-footer bg-secondary d-flex justify-content-end">
                <a href="{% url 'shop_app:add_to_cart' product.id %}" class="link-light h4">
                    <i class="bi bi-cart-plus"></i>
                </a>
            </div>
            <!-- END CARD FOOTER -->


        </div>
    </div>
    {% endfor %}
</div>

{% endblock content %}