ecommerce_proj/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('users_app.urls')),
    path('', include('shop_app.urls')),
    path('payments/', include('payments_app.urls')),
]

shop_app/urls.py
from django.urls import path

from . import views

app_name='shop_app'

urlpatterns = [
    path('', views.index, name='index'),
    path('add-to-cart/<int:product_id>', views.add_to_cart, name='add_to_cart'),
    path('remove-from-cart/<int:cart_item_id>', views.remove_from_cart, name="remove_from_cart"),
    path('update-cart-item/<int:cart_item_id>', views.update_cart_item, name='update_cart_item')
]

users_app/urls.py
from django.urls import path

from . import views

app_name='users_app'

urlpatterns = [
    path('register/', views.register, name='register'),
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),
    path('users/', views.list_users, name='list'),
    path('users/<str:username>', views.detail, name="detail"),
    path('users/edit/<str:username>', views.update, name="update"),
    path('users/follow/<str:username>', views.follow, name="follow")
]

templates/users/detail.html
{% extends 'layout/base.html' %}

{% load static %}

{% block content %}


<div class="row mt-5 pb-5">
    <!-- USER INFO -->
    <div class="col-12 col-lg-3 border-right">
        <h3 class="h3">{{user.username}}</h3>
        <h5 class="h5">{{user.email}}</h5>
        <h5 class="h5">{{user.date_joined}}</h5>
    </div>

    <!-- USER CART -->
    <div class="col-12 col-lg-9">

        <div class="container">
            <h1 class="h1">Cart</h1>
            <!-- Column Labels -->
            <div class="row">
                <div class="col-6">
                    <h4>Product</h4>
                </div>
                <div class="col-4">
                    <h4>Quantity</h4>
                </div>
                <div class="col-2">
                    <h4>Price</h4>
                </div>
            </div>

            <!-- Product rows -->
            <div class="row border-bottom">
                {% for cart_item in user.cart.cart_items.all %}
                <!-- Title and description -->
                <div class="col-6 d-flex align-items-center gap-3  mt-3">
                    <img src="{{cart_item.product.image_url}}" alt="{{cart_item.product.title}}" width="50">
                    <p>
                        {{cart_item.product.title}}
                    </p>
                </div>


                <!-- quantity -->
                <div class="col-4 d-flex align-items-center gap-2 mt-3">
                    <!-- update quantity form -->
                    <form method="POST" class="d-flex align-items-center gap-2">
                        {% csrf_token %}
                        
                        <input type="number" name="quantity" min="1" value="{{cart_item.quantity}}" id="updateform-{{cart_item.id}}" class="form-control update-quantity-form">
                    
                        <!-- <button type="submit" class="btn btn-sm btn-primary">Update</button> -->
                    </form>

                    <!-- delete cart item -->
                    <a href="{% url 'shop_app:remove_from_cart' cart_item.id %}">
                        <button class="btn btn-sm btn-danger">Delete</button>
                    </a>
                </div>


                <!-- price -->
                <div class="col-2 d-flex align-items-center lead mt-3" id="itemsubtotal-{{cart_item.id}}">
                    ${{cart_item.item_subtotal}}
                </div>


                {% endfor %}
            </div>

            <!-- Total price -->
            <div class="row mt-4">
                <div class="col-3 offset-7 d-flex justify-content-end">
                    <h4 class="h4">Total</h4>
                </div>
                <div class="col-2">
                    <h4 id="cart-total-price">${{user.cart.total_price}}</h4>
                </div>
            </div>

            <!-- CHECKOUT BUTTON -->
            <div class="row mt-4">
                <div class="col-2 offset-10">
                    <button class="btn btn-primary" id="checkout-button">Checkout</button>
                </div>
            </div>

        </div>

    </div>


</div>

<script src="{% static 'js/index.js'%}"></script>
<script src="{% static 'js/checkout.js' %}"></script>

{% endblock content %}

templates/users/login.html
{% extends 'layout/base.html' %}

{% block content %}
    

<h1 class="h1 text-center mt-5">Log In</h1>

<form action="{% url 'users_app:login' %}" method="POST" class="d-flex flex-column align-items-center gap-3">
    <!-- Include all fields -->
    <!-- {{ form }} -->


    <!-- render the username field -->
    <fieldset class="form-group">
        <label for="id_username" class="form-label">{{ form.username.label }}</label>
        {{ form.username }}
        
        <!-- render errors for the field if they exist -->
        {% if form.username.errors %}
            {{form.username.errors}}
        {% endif %}
    </fieldset>

    <!-- render the password field -->
    <fieldset class="form-group">
        <label for="id_password" class="form-label">{{ form.password.label }}</label>
        {{ form.password }}

        <!-- render errors for the field if they exist -->
        {% if form.username.errors %}
            {{form.username.errors}}
        {% endif %}
    </fieldset>

    {% csrf_token %}

    <button type="submit" class="btn btn-success">Log In</button>

    <p>Need an account? <a href="{% url 'users_app:register' %}" class="link-primary text-decoration-none">Register</a></p>
</form>



{% endblock content %}

templates/users/register.html
{% extends 'layout/base.html' %}

{% block content %}
    

<h1 class="h1 text-center mt-5">Register</h1>

<form action="{% url 'users_app:register' %}" method="POST" class="d-flex flex-column align-items-center gap-3">
    <!-- Include all fields -->
    <!-- {{ form }} -->

    {% comment %}
        {% for field in form %}

            <fieldset class="form-group">
                <label for="id_{{field.label}}">{{field.label}}</label>
                {{field}}
            </fieldset>
            
        {% endfor %}
    {% endcomment %}

    <!-- render the username field -->
    <fieldset class="form-group">
        <label for="id_username" class="form-label">{{ form.username.label }}</label>
        {{ form.username }}
        
        <!-- render errors for the field if they exist -->
        {% if form.username.errors %}
            {{form.username.errors}}
        {% endif %}
    </fieldset>

    <!-- render the password field -->
    <fieldset class="form-group">
        <label for="id_password" class="form-label">{{ form.password.label }}</label>
        {{ form.password }}

        <!-- render errors for the field if they exist -->
        {% if form.username.errors %}
            {{form.username.errors}}
        {% endif %}
    </fieldset>

    {% csrf_token %}

    <button type="submit" class="btn btn-success">Register</button>

    <p>Have an account? <a href="{% url 'users_app:login' %}" class="link-primary text-decoration-none">Log In</a></p>
</form>

{% endblock content %}