ecommerce_proj/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('users_app.urls')),
    path('', include('shop_app.urls')),
    path('payments/', include('payments_app.urls')),
]

shop_app/urls.py
from django.urls import path

from . import views

app_name='shop_app'

urlpatterns = [
    path('', views.index, name='index'),
    path('add-to-cart/<int:product_id>', views.add_to_cart, name='add_to_cart'),
    path('remove-from-cart/<int:cart_item_id>', views.remove_from_cart, name="remove_from_cart"),
    path('update-cart-item/<int:cart_item_id>', views.update_cart_item, name='update_cart_item')
]

users_app/urls.py
from django.urls import path

from . import views

app_name='users_app'

urlpatterns = [
    path('register/', views.register, name='register'),
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),
    path('users/', views.list_users, name='list'),
    path('users/<str:username>', views.detail, name="detail"),
    path('users/edit/<str:username>', views.update, name="update"),
    path('users/follow/<str:username>', views.follow, name="follow")
]

templates/layout/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <!-- BOOTSTRAP -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM"
        crossorigin="anonymous"></script>

    <!-- BOOTSTRAP ICONS -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.8.1/font/bootstrap-icons.css">

    <!-- BOOTSTRAP MASONRY PLUGIN -->
    <script src="https://cdn.jsdelivr.net/npm/masonry-layout@4.2.2/dist/masonry.pkgd.min.js"
        integrity="sha384-GNFwBvfVxBkLMJpYMOABq3c+d3KnQxudP/mGPkzpZSTYykLBNsZEnG2D9G/X/+7D" crossorigin="anonymous"
        async></script>

    <!-- CUSTOM CSS -->
    <link rel="stylesheet" href="{% static 'css/index.css' %}">

    <!-- AXIOS -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/axios/0.27.2/axios.min.js"></script>

    <!-- STRIPE JS -->
    <script src="https://js.stripe.com/v3/"></script>

    <!-- LOAD LOCAL JS CONFIG -->
    <script src="{% static 'js/config.js' %}"></script>

    <title>eCommerce</title>
</head>

<body>

    {% include 'layout/navbar.html' %}

    <main class="container-fluid pb-5">
        {% block content %}

        {% endblock content %}
    </main>



</body>

</html>

templates/layout/navbar.html
<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <div class="container-fluid">
        <a class="navbar-brand" href="{% url 'shop_app:index' %}">eCommerce</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav"
            aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNav">
            <ul class="navbar-nav">

                {% if request.user.is_authenticated %}
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'users_app:logout'%}">Log Out</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'users_app:detail' request.user.username %}">
                        <i class="bi bi-cart"></i><span id="cart-item-count">({{request.user.cart.item_count}})</span>
                    </a>
                </li>

                {% else %}
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'users_app:register' %}">Register</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'users_app:login' %}">Log In</a>
                </li>
                {% endif %}
            </ul>
        </div>
    </div>
</nav>